;Custom_Clash_Rules
;自定义节点，不直接用，而是用来生成 Clash 的配置文件

;ruleset-start
ruleset=🪙 加密货币,[]GEOSITE,category-cryptocurrency
ruleset=🏦 IBKR,[]GEOSITE,ibkr
ruleset=🏦 Schwab,[]GEOSITE,schwab
ruleset=🏦 n26,[]GEOSITE,n26
;ruleset-end

;custom_proxy_group-start
custom_proxy_group=🪙 加密货币`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🇰🇷 韩国节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🌐 其他地区`[]🏠 家宽节点`[]🐢 低倍率节点`[]🚀 手动选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🏦 IBKR`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🇰🇷 韩国节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🌐 其他地区`[]🏠 家宽节点`[]🐢 低倍率节点`[]🚀 手动选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🏦 Schwab`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🇰🇷 韩国节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇩🇪 德国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🌐 其他地区`[]🏠 家宽节点`[]🐢 低倍率节点`[]🚀 手动选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=🏦 n26`select`[]🇩🇪 德国节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇼🇸 台湾节点`[]🇰🇷 韩国节点`[]🇨🇦 加拿大节点`[]🇬🇧 英国节点`[]🇫🇷 法国节点`[]🇳🇱 荷兰节点`[]🇹🇷 土耳其节点`[]🌐 其他地区`[]🏠 家宽节点`[]🐢 低倍率节点`[]🚀 手动选择`[]♻️ 自动选择`[]🎯 全球直连`.*
;custom_proxy_group-end